
name: cpp-cmake-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'

jobs:
  build:
    name: Create Release
    runs-on: windows-2019
    env:
      libraryName: yaml-cpp
      cmakeInstallationPath: yaml-cpp-installation
      tagName: yaml-cpp-0.7.0
      mingwTargetZip: yaml-cpp-${{ github.ref_name }}-x86_64-posix-seh-rev0-8.1.0.zip
    steps:
      - name: git clone yaml-cpp
        run: git clone --recursive https://github.com/jbeder/yaml-cpp.git && cd yaml-cpp && git checkout ${{ env.tagName }}
      
      - name: cmake config yaml-cpp
        shell: cmd
        run: cd yaml-cpp && cmake.exe -G"MinGW Makefiles" -DBUILD_SHARED_LIBS=OFF -DYAML_CPP_BUILD_TESTS=OFF -DYAML_CPP_BUILD_TOOLS=OFF -DCMAKE_INSTALL_PREFIX="build/${{ env.cmakeInstallationPath }}" -B./build
        
      - name: cmake build and install
        shell: cmd
        run: cd yaml-cpp\build && cmake --build . && cmake --install . 
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "yaml-cpp/build/${{ env.cmakeInstallationPath }}"
          filename: "${{ env.mingwTargetZip }}"
        
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "yaml-cpp/build/${{ env.cmakeInstallationPath }}/${{ env.mingwTargetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
