name: yaml-cpp-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      mingwTargetZip: yaml-cpp-${{ github.ref_name }}-mingw.zip
    steps:
      - name: git clone yaml-cpp
        run: git clone --branch yaml-cpp-0.7.0 https://github.com/jbeder/yaml-cpp.git

      - name: cmake yaml-cpp
        shell: cmd
        run: cd yaml-cpp && cmake.exe -G"MinGW Makefiles" -DBUILD_SHARED_LIBS=OFF -DYAML_CPP_BUILD_TESTS=OFF -DYAML_CPP_BUILD_TOOLS=OFF -DCMAKE_INSTALL_PREFIX="build/yaml-cpp" -B./build
      
      - name: mingw build 
        shell: cmd
        run: cd yaml-cpp\build && mingw32-make install
        
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          path: "yaml-cpp"
          directory: "yaml-cpp/build"
          filename: "${{ env.mingwTargetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.mingwTargetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
